###### 公共 配置 #######
#
##内置Tomcat容器配置
#server:
#  port: 8882
#
##基础配置
#spring:
#  profiles:
#    active: ${ANNOTATION-TEST:dev} #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
#  application:
#    name: annotation-test